version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5070:80" # Mapea el puerto 5070 de tu máquina al puerto 80 del contenedor
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    container_name: platform_ebeacons 
